services:
  ministack:
    # High-performance drop-in replacement for MiniStack
    image: nahuelnucera/ministack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb
      - DEBUG=0
    volumes:
      - './backend/ministack-init:/etc/ministack/init/ready.d'
      - ministack-data:/var/lib/ministack
volumes:
  ministack-data:
