#!/bin/bash
# Updates frontend .env file with backend API URL from SAM deployment

set -e

# shellcheck source=backend/scripts/stack-defaults.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/stack-defaults.sh"

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Determine stack name (from argument, samconfig.toml, or default)
if [ -n "$1" ]; then
  # Use command-line argument if provided
  STACK_NAME="$1"
elif [ -f "samconfig.toml" ]; then
  # Parse samconfig.toml for stack_name (try deploy parameters first, then global)
  CUSTOM_STACK=$(grep -A 20 "^\[default.deploy.parameters\]" samconfig.toml | grep "^stack_name" | head -n 1 | cut -d '=' -f 2 | tr -d ' "')
  if [ -n "$CUSTOM_STACK" ]; then
    STACK_NAME="$CUSTOM_STACK"
  else
    # Fallback to [default.global.parameters] stack_name
    CUSTOM_STACK=$(grep -A 20 "^\[default.global.parameters\]" samconfig.toml | grep "^stack_name" | head -n 1 | cut -d '=' -f 2 | tr -d ' "')
    STACK_NAME="${CUSTOM_STACK:-$DEFAULT_STACK_NAME}"
  fi
else
  # Default if no config found
  STACK_NAME="$DEFAULT_STACK_NAME"
fi

echo "======================================"
echo "Updating Frontend Environment Config"
echo "======================================"
echo ""
echo "Using CloudFormation stack: $STACK_NAME"
echo ""

# Read a stack output, or the empty string if the stack does not export it.
stack_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text 2>/dev/null | sed 's/^None$//'
}

# Step 1: Get API URL from CloudFormation
echo "[1/3] Fetching API Gateway URL from stack: $STACK_NAME..."
API_URL=$(stack_output ReactStocksApiUrl)

if [ -z "$API_URL" ]; then
  echo -e "${RED}✗ Error: Could not fetch API URL from CloudFormation${NC}"
  echo "  Make sure the stack '$STACK_NAME' exists and has been deployed."
  echo "  You can manually get the URL with:"
  echo "    aws cloudformation describe-stacks --stack-name $STACK_NAME"
  exit 1
fi

echo -e "${GREEN}✓ API URL: $API_URL${NC}"
echo ""

# Step 2: Check/create frontend .env file
#
# This resolved $(dirname "$0")/../.. -- from backend/scripts/, the repo root --
# and then wrote EXPO_PUBLIC_BACKEND_URL into <repo-root>/.env, a file Expo does
# not read, while deploy.sh wrote the correct ../frontend/.env. Both now resolve
# the directory through frontend_dir() in stack-defaults.sh so they cannot
# disagree again.
FRONTEND_DIR="$(frontend_dir)"
ENV_FILE="$FRONTEND_DIR/.env"
ENV_EXAMPLE="$FRONTEND_DIR/.env.example"

echo "[2/3] Checking frontend .env file..."

if [ ! -f "$ENV_FILE" ]; then
  if [ -f "$ENV_EXAMPLE" ]; then
    echo -e "${YELLOW}  .env not found, copying from .env.example...${NC}"
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    echo -e "${GREEN}✓ Created $ENV_FILE${NC}"
  else
    echo -e "${RED}✗ Error: .env.example not found in $FRONTEND_DIR${NC}"
    exit 1
  fi
else
  echo -e "${GREEN}✓ Found $ENV_FILE${NC}"
fi
echo ""

# Replace one key in place, preserving every other line — the file also holds
# hand-set values like EXPO_PUBLIC_LOG_LEVEL that no deploy owns.
upsert_env_file() {
  local key="$1" value="$2"
  if grep -qE "^${key}=" "$ENV_FILE"; then
    awk -v k="$key" -v v="$value" \
      '{ if (index($0, k "=") == 1) print k "=" v; else print }' \
      "$ENV_FILE" > "$ENV_FILE.tmp" \
      && mv "$ENV_FILE.tmp" "$ENV_FILE"
    echo -e "${GREEN}✓ Updated $key${NC}"
  else
    if ! grep -q '^# Auto-generated by backend/scripts/update-env.sh$' "$ENV_FILE"; then
      printf '\n# Auto-generated by backend/scripts/update-env.sh\n' >> "$ENV_FILE"
    fi
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    echo -e "${GREEN}✓ Added $key${NC}"
  fi
}

# Step 3: Update the values this deploy owns
echo "[3/3] Updating frontend environment values..."

upsert_env_file EXPO_PUBLIC_BACKEND_URL "$API_URL"

# Optional by design: the app runs auth-optional with these empty, and the
# community edition's template declares no Cognito resources at all. An absent
# output is skipped rather than written as an empty string, which would look
# configured and behave as unset.
USER_POOL_ID=$(stack_output CognitoUserPoolId)
USER_POOL_CLIENT_ID=$(stack_output CognitoUserPoolClientId)
if [ -n "$USER_POOL_ID" ] && [ -n "$USER_POOL_CLIENT_ID" ]; then
  upsert_env_file EXPO_PUBLIC_COGNITO_USER_POOL_ID "$USER_POOL_ID"
  upsert_env_file EXPO_PUBLIC_COGNITO_CLIENT_ID "$USER_POOL_CLIENT_ID"
else
  echo -e "${YELLOW}  No Cognito outputs on this stack — sign-in stays disabled${NC}"
fi

echo ""
echo "======================================"
echo "Environment Update Complete!"
echo "======================================"
echo ""
echo "Frontend .env file updated at:"
echo "  $ENV_FILE"
echo ""
echo "Backend API URL set to:"
echo "  $API_URL"
echo ""
echo "You can now start the frontend with:"
echo "  npm start"
echo ""
